### ISSUE TITLE
Typing in wearhacks.com leads to Error page

### ISSUE THREAD

**Issue by uhztrebor** [wearhacks/main_wearhacks#22]
Alex reports that when typing in "wearhacks.com", it directs her browser (Chrome) to https://www.wearhacks.com, and leads to a "Your Connection is not Private" error page. See screenshot here: https://files.slack.com/files-pri/T02N93RGQ-F0GM79Y5T/screen_shot_2015-12-15_at_9.51.10_am.png

**Comment by makrandgupta** [comment]
that happens because we do not have SSL encryption and for some reason typing in wearhacks.com on alex's computer auto completes to 'https://www.wearhacks.com'. Notice the 's' after 'http'. That s stands for secure. So the browser is trying to access the website using the secure protocol when the website doesnt support that.
